#!/bin/bash
#
#SBATCH -J CMSAv2-FFMSP # A single job name for the array
#SBATCH -p main # Partition
#SBATCH --exclude=luthier[04-10,21-30]
#SBATCH -n 1 # one core
#--SBATCH-- -N 1 # on one node
#--SBATCH-- -t 0-0:17:00 # Running time of 17 mins
#--SBATCH-- --ntasks 4
#SBATCH --mem 8G # Memory request of 7 GB
#SBATCH --array=0-0
#SBATCH -o  bin_outFile_%A_CONF_%a.out 
#SBATCH -e  bin_errFile_%A_CONF_%a.err

#Declaring configurations
declare -a CONF_BIN=(
                                 " -t 10 -th 0.75 -a 0.85 -ant 440 -e 0.05 -tuning" #  Tuning #  

        )
##Binary problems

./ACOElite -i ${1}  ${CONF_BIN[$SLURM_ARRAY_TASK_ID]} >>"resultados75.csv"
